=== IvanRuizAlcala/xml/ejercicio3/ejercicio3.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT libreria (libro+)>
<!ELEMENT libro (titulo, autor+, ISBN, paginas, precio)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT paginas (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== IvanRuizAlcala/xml/ejercicio3/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "ejercicio3.dtd">
<libreria>
<libro>
<titulo>Lenguaje de marcas</titulo>
<autor>Autor2</autor>
<autor>Autorl</autor>
<ISBN></ISBN>
<paginas> l58</paginas>
<precio>15</precio>
</libro>
<libro>
<titulo>XML</titulo>
<autor>Autorl</autor>
<ISBN></ISBN>
<paginas>278</paginas>
<precio>30</precio>
</libro>
</libreria>
